apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-organisasjonsenhet
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-organisasjonsenhet
      rules:
        - alert: toi-organisasjonsenhet
          expr: kube_deployment_status_replicas_available{deployment="toi-organisasjonsenhet"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/3d17391a4fca9112a4810e62b16e8174?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-organisasjonsenhet
          expr: sum(increase(log_messages_errors{app="toi-organisasjonsenhet", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/3d17391a4fca9112a4810e62b16e8174?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-organisasjonsenhet
          expr: sum(increase(log_messages_errors{app="toi-organisasjonsenhet", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/3d17391a4fca9112a4810e62b16e8174?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
