apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid-1
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: toi
      application: toi-cv
      access: readwrite
    - team: toi
      application: toi-veileder
      access: readwrite
    - team: toi
      application: toi-oppfolgingsinformasjon
      access: readwrite
    - team: toi
      application: toi-oppfolgingsperiode
      access: readwrite
    - team: toi
      application: toi-sammenstille-kandidat
      access: readwrite
    - team: toi
      application: toi-kandidatfeed
      access: readwrite
    - team: toi
      application: toi-identmapper
      access: readwrite
    - team: toi
      application: toi-fritatt-kandidatsok
      access: readwrite
    - team: toi
      application: toi-synlighetsmotor
      access: readwrite
    - team: toi
      application: toi-hjemmel
      access: readwrite
    - team: arbeidsgiver-inkludering
      application: arbeidsgiver-inkludering-kafkamanager
      access: readwrite
