apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-livshendelse
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ pdl_host }}
    inbound:
      rules:
        - application: rekrutteringsbistand-kandidatsok-api
  kafka:
    pool: {{ kafka_pool }}
  azure:
    application:
      enabled: true
      allowAllUsers: false
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: PDL_KAFKA_GROUP_ID
      value: {{ pdl_kafka_group_id }}
    - name: PDL_SCOPE
      value: {{ pdl_scope }}
    - name: PDL_URL
      value: {{ pdl_url }}
