apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-siste-14a-vedtak
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-siste-14a-vedtak
      rules:
        - alert: toi-siste-14a-vedtak
          expr: kube_deployment_status_replicas_available{deployment="toi-siste-14a-vedtak"} == 0
          for: 2m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.az.nav.no/goto/6c70c319a9b0bdf45ef87a01c34169ef?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-siste-14a-vedtak
          expr: sum(increase(log_messages_errors{app="toi-siste-14a-vedtak", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.az.nav.no/goto/6c70c319a9b0bdf45ef87a01c34169ef?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-siste-14a-vedtak
          expr: sum(increase(log_messages_errors{app="toi-siste-14a-vedtak", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/6c70c319a9b0bdf45ef87a01c34169ef?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning