apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: dir-stilling-ekstern-v1
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teampam
      application: pam-stilling-dvh-bridge
      access: read
    - team: team-dialog
      application: sf-stilling
      access: read
    - team: toi
      application: toi-kafkamanager
      access: readwrite
    - team: toi
      application: toi-publiser-dir-stillinger
      access: readwrite
