apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-arbeidsgiver-notifikasjon
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: {{notifikasjon_api_host}}
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka_consumer_group_id}}
    - name: NOTIFIKASJON_API_URL
      value: {{notifikasjon_api_url}}
    - name: NOTIFIKASJON_API_SCOPE
      value: {{notifikasjon_api_scope}}
    - name: NOTIFIKASJON_API_HOST
      value: {{notifikasjon_api_host}}