apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-arena-fritatt-kandidatsok
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        databases:
          - name: frkas-db
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_EXTRA_TOPIC
      value: teamarenanais.aapen-arena-kandidatsoekfritatt-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
