apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-kvp
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-kvp
      rules:
        - alert: toi-kvp
          expr: kube_deployment_status_replicas_available{deployment="toi-kvp"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/404117da03436a4a70ae970dd956242e?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-kvp
          expr: sum(increase(log_messages_errors{app="toi-kvp", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/404117da03436a4a70ae970dd956242e?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-kvp
          expr: sum(increase(log_messages_errors{app="toi-kvp", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/404117da03436a4a70ae970dd956242e?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
