apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-arbeidssoekerperiode
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: ARBEIDSSOKER_PERIODE_KAFKA_GROUP_ID
      value: {{arbeidssoker_periode_kafka_group_id}}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
