apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-helseapp
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-helseapp
      rules:
        - alert: toi-helseapp
          expr: kube_deployment_status_replicas_available{deployment="toi-helseapp"} == 0
          for: 5m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.az.nav.no/goto/c1641835aa621b5502b70006b5da88c4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-helseapp
          expr: sum(increase(log_messages_errors{app="toi-helseapp", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Helseappen mener noe er galt
            action: "https://logs.az.nav.no/goto/c1641835aa621b5502b70006b5da88c4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-helseapp
          expr: sum(increase(log_messages_errors{app="toi-helseapp", level="Warning"}[10m])) > 10
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/c1641835aa621b5502b70006b5da88c4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
