apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-ontologitjeneste
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-ontologitjeneste
      rules:
        - alert: toi-ontologitjeneste
          expr: kube_deployment_status_replicas_available{deployment="toi-ontologitjeneste"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/f3cfb7b681c5e589bee4394b4f561525?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: sum(increase(log_messages_errors{app="toi-ontologitjeneste", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/f3cfb7b681c5e589bee4394b4f561525?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-ontologitjeneste
          expr: sum(increase(log_messages_errors{app="toi-ontologitjeneste", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/f3cfb7b681c5e589bee4394b4f561525?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
