apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-tilretteleggingsbehov
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
  kafka:
    pool: {{ kafka_pool }}
  azure:
    application:
      enabled: true
#  gcp:
#    sqlInstances:
#      - type: POSTGRES_12
#        tier: { { gcp_db_tier } }
#        diskAutoresize: { { gcp_disk_autoresize } }
#        databases:
#          - name: tilretteleggingsbehov-db
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_EXTRA_TOPIC
      value: "toi.tillretteleggingsbehov-1"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
  envFrom:
    - secret: toi-tilretteleggingsbehov-servicebruker