apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-identmapper
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-identmapper
      rules:
        - alert: toi-identmapper
          expr: kube_deployment_status_replicas_available{deployment="toi-identmapper"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/4c7948ea6efa0c42e3d9ad231994f074?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-identmapper
          expr: sum(increase(log_messages_errors{app="toi-identmapper", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/4c7948ea6efa0c42e3d9ad231994f074?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-identmapper
          expr: sum(increase(log_messages_errors{app="toi-identmapper", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/4c7948ea6efa0c42e3d9ad231994f074?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
