apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-identmapper
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ pdl_host }}
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: {{ postgres_versjon }}
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        databases:
          - name: identmapping-db
  azure:
    application:
      enabled: true
      allowAllUsers: false
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: KAFKA_MAX_POLL_INTERVAL_MS
      value: "1320000" # 6 sekunder per melding * 200 meldinger + 2 minutter ekstra
    - name: KAFKA_MAX_RECORDS
      value: "200"
    - name: KAFKA_BOOTSTRAP_SERVERS_ONPREM_URL
      value: {{ kafka_bootstrap_on_prem_url }}
    - name: KAFKA_SCHEMA_REGISTRY_ONPREM_URL
      value: {{ kafka_schema_on_prem_url }}
    - name: PDL_SCOPE
      value: {{ pdl_scope }}
    - name: PDL_URL
      value: {{ pdl_url }}
    - name: PDL_KAFKA_GROUP_ID
      value: {{ pdl_kafka_group_id }}
  envFrom:
    - secret: toi-identmapper-servicebruker
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
