apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-veileder
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-veileder
      rules:
        - alert: toi-veileder
          expr: kube_deployment_status_replicas_available{deployment="toi-veileder"} == 0
          for: 2m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.az.nav.no/goto/a84f1fb54d61852439e522893c2d74e0?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-veileder
          expr: sum(increase(log_messages_errors{app="toi-veileder", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.az.nav.no/goto/a84f1fb54d61852439e522893c2d74e0?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-veileder
          expr: sum(increase(log_messages_errors{app="toi-veileder", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/a84f1fb54d61852439e522893c2d74e0?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning