apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-veileder
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 25m
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: {{nom_api_host}}
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_EXTRA_TOPIC
      value: "pto.siste-tilordnet-veileder-v1"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: NOM_API_URL
      value: {{nom_api_url}}
    - name: NOM_API_SCOPE
      value: {{nom_api_scope}}
    - name: NOM_API_HOST
      value: {{nom_api_host}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
