apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-siste-oppfolgingsperiode
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1  # Program er laget for å bare ha en instans. Om det er flere kan det føre til at eldre meldinger kan pushes til nytt topic, etter nye.
  strategy:
    type: Recreate # Recreate sørger for at det ikke er flere instanser av appen som kjører samtidig, og dermed unngår at eldre meldinger kan pushes til nytt topic, etter nye.
  resources:
    limits:
      cpu: 500m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
    streams: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
