apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-siste-oppfolgingsperiode
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 500m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
