apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: siste-oppfolgingsperiode-fra-aktorid-v1
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: toi
      application: toi-siste-oppfolgingsperiode
      access: readwrite
