apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: kandidat-3
  namespace: toi
  labels:
    team: toi
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - application: toi-kandidatfeed
      access: readwrite
    - application: toi-kafkamanager
      access: readwrite
    - application: rekrutteringsbistand-kandidat-indekser
      access: read
    - team: team-ai
      application: cv-consumer
      access: read