apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-synlighetsmotor
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-synlighetsmotor
      rules:
        - alert: toi-synlighetsmotor
          expr: kube_deployment_status_replicas_available{deployment="toi-synlighetsmotor"} == 0
          for: 2m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.az.nav.no/goto/0817a328865629ac11c691f535d4be90?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-synlighetsmotor
          expr: sum(increase(log_messages_errors{app="toi-synlighetsmotor", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.az.nav.no/goto/0817a328865629ac11c691f535d4be90?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-synlighetsmotor
          expr: sum(increase(log_messages_errors{app="toi-synlighetsmotor", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/0817a328865629ac11c691f535d4be90?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
