apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-oppfolgingsinformasjon
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-oppfolgingsinformasjon
      rules:
        - alert: toi-oppfolgingsinformasjon
          expr: kube_deployment_status_replicas_available{deployment="toi-oppfolgingsinformasjon"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/58ffb838af1762f03d0265c087711b2f?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-oppfolgingsinformasjon
          expr: sum(increase(log_messages_errors{app="toi-oppfolgingsinformasjon", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/58ffb838af1762f03d0265c087711b2f?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-oppfolgingsinformasjon
          expr: sum(increase(log_messages_errors{app="toi-oppfolgingsinformasjon", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/58ffb838af1762f03d0265c087711b2f?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
