apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: toi-arbeidsmarked-cv
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: toi-arbeidsmarked-cv
      rules:
        - alert: toi-arbeidsmarked-cv
          expr: kube_deployment_status_replicas_available{deployment="toi-arbeidsmarked-cv"} == 0
          for: 2m
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/3e57e74bc267a21ff6fa7a5448c51c24?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-arbeidsmarked-cv
          expr: sum(increase(log_messages_errors{app="toi-arbeidsmarked-cv", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/3e57e74bc267a21ff6fa7a5448c51c24?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: toi-arbeidsmarked-cv
          expr: sum(increase(log_messages_errors{app="toi-arbeidsmarked-cv", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/3e57e74bc267a21ff6fa7a5448c51c24?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
