apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: toi-arbeidsmarked-cv
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka_consumer_group_id}}
    - name: ARBEIDSMARKED_CV_KAFKA_GROUP_ID
      value: {{arbeidsmarked_cv_kafka_group_id}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
