name: toi-publisering-til-arbeidsplassen

on:
  push:
    paths:
      - apps/toi-publisering-til-arbeidsplassen/**
      - .github/workflows/deploy-toi-publisering-til-arbeidsplassen.yaml
      - .github/workflows/deploy-toi-template.yaml
      - buildSrc/**
      - technical-libs/testrapid

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/send-saksbehandler-til-arbeidsplassen
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
