name: toi-oppfolgingsinformasjon

on:
  push:
    paths:
    - apps/toi-oppfolgingsinformasjon/**
    - .github/workflows/deploy-toi-oppfolgingsinformasjon.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**
    - technical-libs/testrapid

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/logback4
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
