name: toi-veileder

on:
  push:
    paths:
    - apps/toi-veileder/**
    - .github/workflows/deploy-toi-veileder.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/logback8
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
