on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deploy_dev_branch:
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Java v25
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Gradle test and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: ${{ inputs.app_name }}
        run: |
          chmod +x ./gradlew
          ./gradlew :apps:${APP_NAME}:test :apps:${APP_NAME}:build
      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-report
          path: apps/${{ inputs.app_name }}/build/reports/tests/test
      - name: Push docker image to GAR
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: toi
          image_suffix: ${{ inputs.app_name }}
          dockerfile: apps/${{ inputs.app_name }}/Dockerfile
          docker_context: apps/${{ inputs.app_name }}
          tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
          build_args: |
            APP_NAME=${{ inputs.app_name }}

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    needs: build-and-publish
    if: github.ref == 'refs/heads/main' || github.ref == inputs.deploy_dev_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ inputs.app_name }}/nais.yaml
          VARS: apps/${{ inputs.app_name }}/nais-dev.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    needs: [ build-and-publish, deploy-to-dev-gcp ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/${{ inputs.app_name }}/nais.yaml,apps/${{ inputs.app_name }}/alerts.yaml
          VARS: apps/${{ inputs.app_name }}/nais-prod.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}

  call-trivy-security-scan:
    needs: build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@v15
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
