name: Deploy rapid-topic to dev

on:
  push:
    branches:
      - main
      - bruk-zizmor-paa-workflows
    paths:
      - .github/workflows/deploy-topic-to-dev.yaml
      - topic-dev.yaml

jobs:
  deploy-rapid-to-dev:
    name: Deploy rapid-topic to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: topic-dev.yaml
    permissions:
      contents: read
      id-token: write
      security-events: write
