name: Deploy Opensearch stilling prod
on:
  push:
    branches:
      - main
    paths:
      - apps/toi-stilling-indekser/opensearch.yaml
      - .github/workflows/deploy-opensearch-stilling-prod.yml
jobs:
  deploy-opensearch:
    name: Deploy Opensearch instance to cluster
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/toi-stilling-indekser/opensearch.yaml
          VARS: apps/toi-stilling-indekser/nais-prod.yaml
