name: Deploy dir-stilling-ekstern-topic to dev

on:
  push:
    branches:
      - main
      - ny_app_for_publisering_til_dir_topic
    paths:
      - .github/workflows/deploy-topic-dir-stilling-ekstern-to-dev.yaml
      - apps/toi-publiser-dir-stillinger/dir-stilling-ekstern-topic-dev.yaml

jobs:
  deploy-dir-stilling-ekstern-topic-to-dev:
    name: Deploy dir-stilling-ekstern-topic to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/toi-publiser-dir-stillinger/dir-stilling-ekstern-topic-dev.yaml
    permissions:
      contents: read
      id-token: write
      security-events: write
