name: Deploy dir-stilling-ekstern-topic to prod

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-topic-dir-stilling-ekstern-to-prod.yaml
      - apps/toi-publiser-dir-stillinger/dir-stilling-ekstern-topic-prod.yaml

jobs:
  deploy-dir-stilling-ekstern-topic-to-prod:
    name: Deploy dir-stilling-ekstern-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/toi-publiser-dir-stillinger/dir-stilling-ekstern-topic-prod.yaml
    permissions:
      contents: read
      id-token: write
      security-events: write
