name: toi-sammenstille-kandidat

on:
  push:
    paths:
    - apps/toi-sammenstille-kandidat/**
    - .github/workflows/deploy-toi-sammenstille-kandidat.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/feature/asr
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
