name: Deploy Opensearch stilling dev
on:
  push:
    branches:
      - main
      - bruk-zizmor-paa-workflows
    paths:
      - apps/toi-stilling-indekser/opensearch.yaml
      - .github/workflows/deploy-opensearch-stilling-dev.yml
jobs:
  deploy-opensearch:
    name: Deploy Opensearch instance to cluster
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/toi-stilling-indekser/opensearch.yaml
          VARS: apps/toi-stilling-indekser/nais-dev.yaml
