name: toi-identmapper

on:
  push:
    paths:
    - apps/toi-identmapper/**
    - .github/workflows/deploy-toi-identmapper.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**
    - technical-libs/testrapid

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/oppdater-r-r-identmapper
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
