name: toi-siste-14a-vedtak

on:
  push:
    paths:
    - apps/toi-siste-14a-vedtak/**
    - .github/workflows/deploy-toi-siste-14a-vedtak.yaml
    - .github/workflows/deploy-toi-template.yaml
    - buildSrc/**

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy-toi-template.yaml
    with:
      app_name: ${{ github.workflow }}
      deploy_dev_branch: refs/heads/logback6
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      security-events: write
