name: 'Oppdater Docker baseimage: toi-stilling-indekser'
on:
  schedule:
    - cron: '32 6 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-stilling-indekser
      deploy-workflow-filnavn: deploy-toi-stilling-indekser.yaml
    permissions:
      id-token: write
      actions: write
