name: 'Oppdater Docker baseimage: toi-ontologitjeneste'
on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-ontologitjeneste
      deploy-workflow-filnavn: deploy-toi-ontologitjeneste.yaml
    permissions:
      id-token: write
      actions: write
