name: 'Oppdater Docker baseimage: toi-publiser-dir-stillinger'
on:
  schedule:
    - cron: '8 4 * * *'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-publiser-dir-stillinger
      deploy-workflow-filnavn: deploy-toi-publiser-dir-stillinger.yaml
    permissions:
      id-token: write
      actions: write
