name: 'Oppdater Docker baseimage: toi-siste-oppfolgingsperiode'
on:
  schedule:
    - cron: '37 6 * * 4'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-siste-oppfolgingsperiode
      deploy-workflow-filnavn: deploy-toi-siste-oppfolgingsperiode.yaml
    permissions:
      id-token: write
      actions: write
