name: 'Oppdater Docker baseimage: toi-arbeidsgiver-notifikasjon'
on:
  schedule:
    - cron: '13 5 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-arbeidsgiver-notifikasjon
      deploy-workflow-filnavn: deploy-toi-arbeidsgiver-notifikasjon.yaml
    permissions:
      id-token: write
      actions: write
