name: 'Oppdater Docker baseimage: toi-siste-14a-vedtak'
on:
  schedule:
    - cron: '20 4 * * *'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-siste-14a-vedtak
      deploy-workflow-filnavn: deploy-toi-siste-14a-vedtak.yaml
    permissions:
      id-token: write
      actions: write
