name: 'Oppdater Docker baseimage: toi-arbeidssoekeropplysninger'
on:
  schedule:
    - cron: '24 3 * * *'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-arbeidssoekeropplysninger
      deploy-workflow-filnavn: deploy-toi-arbeidssoekeropplysninger.yaml
    permissions:
      id-token: write
      actions: write
