name: 'Oppdater Docker baseimage: toi-helseapp'
on:
  schedule:
    - cron: '36 5 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-helseapp
      deploy-workflow-filnavn: deploy-toi-helseapp.yaml
    permissions:
      id-token: write
      actions: write
