name: 'Oppdater Docker baseimage: toi-oppfolgingsinformasjon'
on:
  schedule:
    - cron: '13 6 * * 3'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-oppfolgingsinformasjon
      deploy-workflow-filnavn: deploy-toi-oppfolgingsinformasjon.yaml
    permissions:
      id-token: write
      actions: write
