name: 'Oppdater Docker baseimage: toi-hull-i-cv'
on:
  schedule:
    - cron: '40 5 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-hull-i-cv
      deploy-workflow-filnavn: deploy-toi-hull-i-cv.yaml
    permissions:
      id-token: write
      actions: write
