name: 'Oppdater Docker baseimage: toi-geografi'
on:
  schedule:
    - cron: '32 5 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-geografi
      deploy-workflow-filnavn: deploy-toi-geografi.yaml
    permissions:
      id-token: write
      actions: write
