name: 'Oppdater Docker baseimage: toi-identmapper'
on:
  schedule:
    - cron: '13 6 * * 2'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-identmapper
      deploy-workflow-filnavn: deploy-toi-identmapper.yaml
    permissions:
      id-token: write
      actions: write
