name: 'Oppdater Docker baseimage: toi-publisering-til-arbeidsplassen'
on:
  schedule:
    - cron: '12 4 * * *'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: toi-publisering-til-arbeidsplassen
      deploy-workflow-filnavn: deploy-toi-publisering-til-arbeidsplassen.yaml
    permissions:
      id-token: write
      actions: write
